Fix bazelisk for non-direnv users (#1)
* Fix bazelisk for non-direnv users

As per the upstream instructions, bazelisk should really be installed
under `tools/bazel`. The `tools/bin/bazel` symlink is only useful for
`direnv` users.

https://github.com/bazelbuild/bazelisk#other-features
> If tools/bazel exists in your workspace root and is executable,
> Bazelisk will run this file, instead of the Bazel version it
> downloaded.

Upstream Bazel behaves the same way. I.e. the presence of an
executable `tools/bazel` causes bazel to defer to that executable.

Now instead of seeing this error:

    $ bazel test //au/...
    ERROR: The project you're trying to build requires Bazel 5.3.0 (specified in /home/pschrader/repos/au/.bazelversion), but it wasn't found in /usr/bin.

    You can install the required Bazel version via apt:
      sudo apt update && sudo apt install bazel-5.3.0

    If this doesn't work, check Bazel's installation instructions for help:
      https://docs.bazel.build/versions/master/install-ubuntu.html

I can build the tests.

* Update the README